#!/bin/bash

steamcmd_dir="$HOME/.steam/steamcmd"
install_dir="$steamcmd_dir/dstserver"
cluster_name="${1:-MyDediServer}"
dontstarve_dir="$HOME/.klei/DoNotStarveTogether"

function fail()
{
	echo Error: "$@" >&2
	exit 1
}

function check_for_file()
{
	if [ ! -e "$1" ]; then
		fail "Missing file: $1"
	fi
}

function install_mods()
{
    # get all mods from your current clusters
    grep workshop- $dontstarve_dir/*/*/modoverrides.lua | \
        perl -pe 's/.*-(\w+)\".*/ServerModSetup("$1")/' | \
        sort -Vu >> "$install_dir/mods/dedicated_server_mods_setup.lua"
}

function run()
{
    echo "Starting: $cluster_name"
    echo "!!!  !!!"

    cd "$steamcmd_dir" || fail "Missing $steamcmd_dir directory!"

    check_for_file "steamcmd.sh"
    check_for_file "$dontstarve_dir/$cluster_name/cluster.ini"
    check_for_file "$dontstarve_dir/$cluster_name/cluster_token.txt"
    check_for_file "$dontstarve_dir/$cluster_name/Master/server.ini"
    check_for_file "$dontstarve_dir/$cluster_name/Caves/server.ini"


    steamcmd +force_install_dir "$install_dir" +login anonymous +app_update 343050 validate +quit

    check_for_file "$install_dir/bin"

    cd "$install_dir/bin" || fail

    install_mods

    run_shared=(./dontstarve_dedicated_server_nullrenderer)
    run_shared+=(-cluster "$cluster_name")
    run_shared+=(-monitor_parent_process $$)

    "${run_shared[@]}" -shard Caves  | sed 's/^/Caves:  /' &
    "${run_shared[@]}" -shard Master | sed 's/^/Master: /'
}

run
